#####
# This is example config. Edit and copy this for use.
#####

# Bot token
token = "SUPER_SECRET_TOKEN_HERE"
# Command prefix
prefix = "ay."

### Log levels ###
[logLevels]
default = "info"
boot = "info"
message = "warn"
database = "warn"

### Database Settings ###
[database]
# Hostname
host = "localhost"
# Port (Default value: 3306)
port = 3306
# Database name
database = "DATABASE_NAME_HERE"
# User name
user = "USER_NAME_HERE"
# Password
password = "PASSWORD_HERE"
# Tables prefix
prefix = ""
